version: "3.9"
services:
  postgres-db:
    image: postgres:15
    container_name: projectcanary-db
    environment:
      POSTGRES_USER: project_canary_takehome
      POSTGRES_PASSWORD: giveemissionsthebird
      POSTGRES_DB: project_canary_takehome
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data:/data  # Mount the local 'data' folder containing CSVs
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount initialization scripts

volumes:
  db_data:
